// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import "aos/dist/aos.css";
import NavbarServerComponent from "@/components/Theme1/NavberServerComponent";
import Footer from "@/components/Theme1/Footer";
// import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Business Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#ECF3F1] text-black px-2">
        {/* <Navbar /> */}
        <NavbarServerComponent></NavbarServerComponent>
        {children}
        <div className="flex justify-center py-8" id="footer">
          <Footer />
        </div>

      </body>
    </html>
  );
}






// import TestNavber from "@/components/TestNavber";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });